name: CD

on:
  workflow_run:
    workflows: ["CI"]
    types: [completed]


permissions:
  contents: write

jobs:
  detect-version:
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'success'
    steps:
      - uses: actions/checkout@v4
      - id: set_tag
        shell: bash
        run: |
          latest_tag=$(git tag --list "v*" --sort=-v:refname | head -n1)
          version=$(grep -Pom1 '(?<=version = ")[^"]+(?=")' Cargo.toml)
          echo "latest_tag=$latest_tag"
          echo "version=$version"
          if [[ "$latest_tag" != "v$version" ]]; then
            echo "compare=$([[ "$latest_tag" != "v$version" ]] && echo true || echo false)"
            echo "tag=v$version" >> $GITHUB_OUTPUT
            echo "tag=v$version"
            echo "is_bump=true" >> $GITHUB_OUTPUT
            echo "is_bump=true"
          else
            echo "compare=$([[ "$latest_tag" != "v$version" ]] && echo true || echo false)"
            echo "tag=dev-latest" >> $GITHUB_OUTPUT
            echo "tag=dev-latest"
            echo "is_bump=false" >> $GITHUB_OUTPUT
            echo "is_bump=false"
          fi
          cat $GITHUB_OUTPUT

    outputs:
      tag: ${{ steps.set_tag.outputs.tag }}
      is_bump: ${{ steps.set_tag.outputs.is_bump }}


  build:
    needs: detect-version
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            binary: dankbytes
            simple_target: x86_64-linux
          - os: macos-latest
            target: x86_64-apple-darwin
            binary: dankbytes
            simple_target: x86_64-macos
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            binary: dankbytes.exe
            simple_target: x86_64-windows

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          target: ${{ matrix.target }}
          
      - name: Cache cargo registry and target
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock', '**/Cargo.toml') }}-v1
          restore-keys: |
            ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock', '**/Cargo.toml') }}-
            ${{ runner.os }}-cargo-

      - name: Build
        shell: bash
        run: |
          if [[ "${{ needs.detect-version.outputs.is_bump }}" == "true" ]]; then
            cargo build --release --target ${{ matrix.target }}
          fi
          cargo build --target ${{ matrix.target }}

      - name: Set archive name
        id: archive
        shell: bash
        run: |
          if [[ "${{ needs.detect-version.outputs.is_bump }}" == "true" ]]; then
            echo "archive=dankbytes-${{ needs.detect-version.outputs.tag }}-${{ matrix.simple_target }}.tar.gz" >> $GITHUB_OUTPUT
            echo "archive_win=dankbytes-${{ needs.detect-version.outputs.tag }}-${{ matrix.simple_target }}.zip" >> $GITHUB_OUTPUT
          fi
          echo "archive_debug=dankbytes-dev-${{ matrix.simple_target }}.tar.gz" >> $GITHUB_OUTPUT
          echo "archive_debug_win=dankbytes-dev-${{ matrix.simple_target }}.zip" >> $GITHUB_OUTPUT

      - name: Package (Unix)
        shell: bash
        if: matrix.os != 'windows-latest'
        run: |
          if [[ "${{ needs.detect-version.outputs.is_bump }}" == "true" ]]; then
            cd ${{ github.workspace }}
            tar -czf ./dankbytes-${{ needs.detect-version.outputs.tag }}-${{ matrix.simple_target }}.tar.gz -C target/${{ matrix.target }}/release ${{ matrix.binary }}
          fi
          cd ${{ github.workspace }}
          tar -czf ./dankbytes-dev-${{ matrix.simple_target }}.tar.gz -C target/${{ matrix.target }}/debug ${{ matrix.binary }}

      - name: Package (Windows)
        if: matrix.os == 'windows-latest'
        shell: bash
        run: |
          if [[ "${{ needs.detect-version.outputs.is_bump }}" == "true" ]]; then
            WORKSPACE=$(echo "${{ github.workspace }}" | sed 's/\\/\//g' | sed 's/://')
            cd "/$WORKSPACE"
            7z a -tzip "./dankbytes-${{ needs.detect-version.outputs.tag }}-${{ matrix.simple_target }}.zip" "./target/${{ matrix.target }}/release/${{ matrix.binary }}"
          fi
          7z a -tzip "./dankbytes-dev-${{ matrix.simple_target }}.zip" "./target/${{ matrix.target }}/debug/${{ matrix.binary }}"

      - name: Upload to Release
        if: needs.detect-version.outputs.is_bump == 'true'
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ needs.detect-version.outputs.tag }}
          name: 🚀 ${{ needs.detect-version.outputs.tag }}
          prerelease: false
          draft: false
          body: |
            release ${{ needs.detect-version.outputs.tag }} from commit ${{ github.sha }}
          files: ${{ matrix.os == 'windows-latest' && steps.archive.outputs.archive_win || steps.archive.outputs.archive }}

      - name: Upload to Dev
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: dev-latest
          name: ⚠️ dev-latest
          prerelease: true
          draft: false
          body: |
            release dev-latest from commit ${{ github.sha }}
          files: ${{ matrix.os == 'windows-latest' && steps.archive.outputs.archive_debug_win || steps.archive.outputs.archive_debug }}
