name: CI

on:
  push:
    branches: [main]
    paths-ignore:
      - 'justfile'
      - 'LICENSE'
      - 'README.md'
      - 'rustfmt.toml'
  pull_request:
    branches: [main]
    paths-ignore:
      - '.github/**'
      - 'justfile'
      - 'LICENSE'
      - 'README.md'
      - 'rustfmt.toml'

jobs:
  check:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Cache target directory
        uses: actions/cache@v4
        id: cache
        with:
          path: target
          key: |
            ${{ runner.os }}-target-${{ hashFiles('Cargo.toml') }}-
            ${{ runner.os == 'windows-latest' && 'windows-deps' || '' }}
          restore-keys: |
            ${{ runner.os }}-target-
            ${{ runner.os == 'windows-latest' && 'windows-deps' || '' }}

      - name: Cache cargo registry
        uses: actions/cache@v4
        with:
          path: ~/.cargo/registry
          key: ${{ runner.os }}-cargo-registry-${{ hashFiles('Cargo.toml') }}
          restore-keys: ${{ runner.os }}-cargo-registry

      - name: Fmt
        run: cargo fmt -- --check
      - name: Clippy
        run: cargo clippy -- -D warnings
      - name: Clippy (release)
        run: cargo clippy --release -- -D warnings
      - name: Build
        run: cargo build --verbose

