name: CI

on:
  push:
    branches: [
      main
    ]
  pull_request:
    branches: [
      main
    ]
  workflow_dispatch:
    inputs:
      run_tests:
        description: 'Run tests'
        required: true
        default: 'true'
      run_lint:
        description: 'Run lint'
        required: true
        default: 'true'
      run_format:
        description: 'Run format'
        required: true
        default: 'true'
      run_build:
        description: 'Run build'
        required: true
        default: 'true'
  
env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1
  
jobs:
  check:
    name: Check ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          - os: macos-latest
            target: x86_64-apple-darwin
          - os: windows-latest
            target: x86_64-pc-windows-msvc
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          components: rustfmt, clippy

      - name: Install dependencies
        run: cargo fetch

      - name: Run tests
        if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.run_tests == 'true' || github.event_name != 'workflow_dispatch' }}
        run: cargo test --all --verbose

      - name: Run lint
        if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.run_lint == 'true' || github.event_name != 'workflow_dispatch' }}
        run: cargo clippy --all --all-targets --all-features -- -D warnings

      - name: Run format
        if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.run_format == 'true' || github.event_name != 'workflow_dispatch' }}
        run: cargo fmt --all -- --check

      - name: Run build
        if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.run_build == 'true' || github.event_name != 'workflow_dispatch' }}
        run: cargo build --all --release
